---
- name: Get IP interface info from Cisco FTD
  hosts: cisco_ftd
  gather_facts: no
  become: true  # Use sudo if needed
  tasks:
    - name: Display a custom message from Cisco FTD
      debug:
        msg: "Hello from Cisco FTD!"
