---
- name: Get IP interface info from Cisco FTD
  hosts: cisco_ftd
  become: true  # Use sudo if needed
  tasks:
    - name: Run the 'uptime' command
      ansible.builtin.command: uptime
      register: uptime_output

    - name: Show the command output
      ansible.builtin.debug:
        var: uptime_output.stdout
