---
- name: Get IP interface info from Cisco FTD
  hosts: cisco_ftd
  gather_facts: no
  become: true  # Use sudo if needed
  tasks:
    - name: Display a custom message from Cisco FTD
      debug:
        msg: "Hello from Cisco FTD!"
        
    - name: Run the 'show interface ip brief' command
      ansible.builtin.command: show interface ip brief
      register: output

    - name: Show the command output
      ansible.builtin.debug:
        var: output.stdout
